name: Deploy do Azure

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install psycopg2-binary

            - name: Run script
              run: |
                    python wgraj_do_bazy.py
            
            - name: Deploy to Azure PostgreSQL
              uses: azure/postgresql-action@v1
              with:
                server-name: ${{ secrets.AZURE_POSTGRESQL_SERVER }}
                server-username: ${{ secrets.AZURE_POSTGRESQL_USERNAME }}
                server-password: ${{ secrets.AZURE_POSTGRESQL_PASSWORD }}
                database-name: ${{ secrets.AZURE_POSTGRESQL_DATABASE }}
                sql-file: 'wgraj_do_bazy.sql'
                   